version: '3.8'

services:
  mysql:
    image: bitnami/mysql:8.3
    container_name: mysql
    ports:
      - '3306:3306'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=finnotech
    networks:
      - localnet

  redis:
    container_name: redis
    image: redis/redis-stack:7.2.0-v8
    ports:
      - 6379:6379
      - 13333:8001
    networks:
      - localnet

networks:
  localnet:
    driver: bridge
