version: '3.8'

services:
  mysql:
    image: bitnami/mysql:8.3
    container_name: mysql
    ports:
      - '3306:3306'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=finnotech
    networks:
      - localnet

networks:
  localnet:
    driver: bridge
